
import { Need, NeedStatus, TaskType, ExpertProfile, TrustTier, EnglishLevel, MatchRecord, MatchStatus, ExpertTier, DataProductType, AdminTemplate } from '../types';

export const MOCK_EXPERTS: ExpertProfile[] = [
  {
    id: 'exp-1',
    name: '张伟 博士',
    domainTags: ['NLP', '法律合规', 'LLM评审'],
    summaryExperience: '10年以上法律科技经验，精通中国监管框架及法律文本分析。曾主导多个法律大模型的数据清洗与评估体系建设。',
    englishLevel: EnglishLevel.PROFICIENT,
    preferredWeeklyHours: 15,
    rateRange: '¥600 - ¥900 / 小时',
    verificationLink: 'https://linkedin.com/in/zhangwei',
    skills: ['NLP', 'Legal AI', 'Risk Assessment'],
    languages: ['Chinese', 'English'],
    hobbies: ['书法', '围棋'],
    certifications: [{ name: '中国法律职业资格', issuer: '司法部', year: '2012' }],
    portfolioUrl: '',
    additionalLinks: [],
    location: { country: 'China', state: 'Beijing', city: 'Beijing', postalCode: '100000', dob: '1985-01-01', isAuthorized: true, locationSameAsPhysical: true },
    availabilityToStart: '立即',
    timezone: 'UTC+8',
    workingHours: [],
    domainInterests: ['Legal'],
    minCompensationFT: 0,
    minCompensationPT: 600,
    comms: { emailEnabled: true, smsEnabled: true, fullTimeOpps: true, partTimeOpps: true, referralOpps: true, jobNotifications: true, workUpdates: true },
    workExperiences: [{ id: 'w1', company: '法律科技领先企业', role: '首席技术专家', startDate: '2018-01', isCurrent: true, description: '负责构建法律大模型的训练评估体系。' }],
    educations: [{ id: 'e1', institution: '北京大学', degree: '博士', field: '计算机科学', graduationYear: '2014' }],
    trustTier: TrustTier.PROVEN,
    riskFlags: [],
  },
  {
    id: 'exp-2',
    name: 'Linda Schmidt',
    domainTags: ['Medical AI', 'Radiology', 'Dataset Curation'],
    summaryExperience: 'Senior Radiologist with 8 years of experience in AI-assisted diagnosis. Expertise in curating high-quality medical imaging datasets for model fine-tuning.',
    englishLevel: EnglishLevel.NATIVE,
    preferredWeeklyHours: 10,
    rateRange: '€150 - €220 / Hour',
    verificationLink: 'https://orcid.org/linda-schmidt',
    skills: ['Radiology', 'Data Labeling', 'Clinical Trials'],
    languages: ['German', 'English'],
    hobbies: ['Photography'],
    certifications: [{ name: 'Medical Board Certified', issuer: 'BÄK', year: '2016' }],
    portfolioUrl: '',
    additionalLinks: [],
    location: { country: 'Germany', state: 'Berlin', city: 'Berlin', postalCode: '10115', dob: '1982-04-12', isAuthorized: true, locationSameAsPhysical: true },
    availabilityToStart: '1 Week',
    timezone: 'UTC+1',
    workingHours: [],
    domainInterests: ['Medical'],
    minCompensationFT: 0,
    minCompensationPT: 120,
    comms: { emailEnabled: true, smsEnabled: true, fullTimeOpps: false, partTimeOpps: true, referralOpps: true, jobNotifications: true, workUpdates: true },
    workExperiences: [],
    educations: [],
    trustTier: TrustTier.PROVEN,
    riskFlags: [],
  },
  {
    id: 'exp-3',
    name: 'Chen Wei',
    domainTags: ['Python', 'System Red Teaming', 'Safety'],
    summaryExperience: 'Software Security Engineer specialized in LLM jailbreaking and safety alignment testing. Previously at a top-tier global cloud provider.',
    englishLevel: EnglishLevel.PROFICIENT,
    preferredWeeklyHours: 20,
    rateRange: '¥500 - ¥800 / 小时',
    verificationLink: '',
    skills: ['Cybersecurity', 'Python', 'Adversarial Attacks'],
    languages: ['Chinese', 'English'],
    hobbies: [],
    certifications: [],
    portfolioUrl: '',
    additionalLinks: [],
    location: { country: 'China', state: 'Guangdong', city: 'Shenzhen', postalCode: '518000', dob: '1991-09-30', isAuthorized: true, locationSameAsPhysical: true },
    availabilityToStart: '立即',
    timezone: 'UTC+8',
    workingHours: [],
    domainInterests: ['Security'],
    minCompensationFT: 0,
    minCompensationPT: 500,
    comms: { emailEnabled: true, smsEnabled: true, fullTimeOpps: true, partTimeOpps: true, referralOpps: true, jobNotifications: true, workUpdates: true },
    workExperiences: [],
    educations: [],
    trustTier: TrustTier.SCREENED,
    riskFlags: [],
  },
  {
    id: 'exp-4',
    name: '刘芳',
    domainTags: ['多模态', '视觉模型', '投研分析'],
    summaryExperience: '前视觉AI初创公司首席算法工程师。在多模态理解与生成式AI的Post-training数据构建方面有极深造诣。',
    englishLevel: EnglishLevel.PROFICIENT,
    preferredWeeklyHours: 12,
    rateRange: '¥800 - ¥1200 / 小时',
    verificationLink: 'https://scholar.google.com/liufang',
    skills: ['Computer Vision', 'Multimodal', 'Financial Modeling'],
    languages: ['Chinese', 'English'],
    hobbies: ['Chess', 'Travelling'],
    certifications: [],
    portfolioUrl: '',
    additionalLinks: [],
    location: { country: 'China', state: 'Shanghai', city: 'Shanghai', postalCode: '200000', dob: '1992-05-15', isAuthorized: true, locationSameAsPhysical: true },
    availabilityToStart: '立即',
    timezone: 'UTC+8',
    workingHours: [],
    domainInterests: ['AI', 'Finance'],
    minCompensationFT: 0,
    minCompensationPT: 800,
    comms: { emailEnabled: true, smsEnabled: true, fullTimeOpps: true, partTimeOpps: true, referralOpps: true, jobNotifications: true, workUpdates: true },
    workExperiences: [{ id: 'w2', company: '视觉AI初创公司', role: '首席算法', startDate: '2019-06', isCurrent: true, description: '主导多模态大模型的研发。' }],
    educations: [{ id: 'e2', institution: '清华大学', degree: '硕士', field: '人工智能', graduationYear: '2018' }],
    trustTier: TrustTier.SCREENED,
    riskFlags: [],
  }
];

export const MOCK_NEEDS: Need[] = [
  {
    id: 'need-101',
    customerId: 'cust-1',
    customerOrgName: '神经网络科技 (NeuralTech)',
    domainArea: '法律推理评估 (Round 2: 替换中)',
    masterDomain: 'Legal',
    subDomain: 'Chinese Corporate Law',
    taskType: TaskType.REVIEW,
    expertTier: ExpertTier.PRINCIPAL,
    dataProductType: DataProductType.EVAL,
    taskDescription: '评审500组中文法律QA对。第一轮专家因预算问题退出。现在需要寻找更资深的专家，且必须具备执业背景。',
    intensityHours: 15,
    timeline: '4周',
    languageRequirement: '中文（母语）',
    budgetRange: '¥800 - ¥1200 / 小时',
    status: NeedStatus.SHORTLISTED,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    shortlist: ['exp-1', 'exp-4'],
    shortlistReviewStatuses: {
      'exp-1': { status: 'approved', timestamp: new Date(Date.now() - 3600000).toISOString() },
      'exp-4': { status: 'declined', reason: '项目背景太侧重纯视觉，我们需要更懂金融法律的专家。', timestamp: new Date(Date.now() - 7200000).toISOString() }
    },
    roundIndex: 2,
    clarificationLog: [
      { id: 'm1', author: 'admin', text: '已收到您的拒绝反馈，我们正在为您联系具有证券法律背景的候选人。', timestamp: new Date(Date.now() - 5000000).toISOString() }
    ],
    isApproved: true,
    pendingActionBy: 'admin',
    replacementCount: 1,
    ttfs_hours: 12
  },
  {
    id: 'need-raw-001',
    customerId: 'cust-2',
    customerOrgName: '药研智造 (PharmaGen)',
    domainArea: '待结构化：抗体研发红队对抗',
    taskType: TaskType.REDTEAM,
    taskDescription: '测试模型在生物武器相关指令上的防御力。需要具备高级生物化学背景的专家。',
    intensityHours: 5,
    timeline: '2周',
    languageRequirement: '中文/英文',
    budgetRange: '待定',
    status: NeedStatus.SUBMITTED,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    shortlist: [],
    shortlistReviewStatuses: {},
    roundIndex: 1,
    clarificationLog: [],
    pendingActionBy: 'admin',
    isApproved: false,
    replacementCount: 0
  },
  {
    id: 'need-intro-001',
    customerId: 'cust-3',
    customerOrgName: '金融之眼 (FinEye)',
    domainArea: '多模态报表分析',
    masterDomain: 'Finance',
    subDomain: 'Investment Research',
    taskType: TaskType.CONSULTING,
    dataProductType: DataProductType.RLHF,
    taskDescription: '对模型生成的财报分析进行真实性核查与风格对齐。',
    intensityHours: 10,
    timeline: '3个月',
    languageRequirement: '英文',
    budgetRange: '$150/hr',
    status: NeedStatus.INTRO,
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    shortlist: ['exp-4'],
    shortlistReviewStatuses: { 'exp-4': { status: 'approved' } },
    roundIndex: 1,
    clarificationLog: [],
    pendingActionBy: 'customer',
    isApproved: true,
    aiSummary: '1. 领域：财务报表多模态分析；2. 核心任务：Hallucination Check & Style Alignment；3. 目标：高保真研报输出。',
    replacementCount: 0,
    ttfs_hours: 24,
    ttd_days: 3
  }
];

export const MOCK_MATCHES: MatchRecord[] = [
  {
    id: 'match-101',
    needId: 'need-101',
    expertId: 'exp-4',
    roundIndex: 2,
    status: MatchStatus.REJECTED_PREVIEW,
    shortlistedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    rejectReason: '客户要求的交付节奏太快，无法保证质量。',
    opportunitySummary: '法律推理大模型评估 (Round 2)',
    payRange: '¥1,000 / hr'
  },
  {
    id: 'match-active-1',
    needId: 'need-intro-001',
    expertId: 'exp-4',
    roundIndex: 1,
    status: MatchStatus.MEETING_SCHEDULED,
    shortlistedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    meetingScheduledAt: new Date(Date.now() + 86400000).toISOString(),
    opportunitySummary: '多模态报表分析'
  },
  {
    id: 'match-history-1',
    needId: 'need-old-1',
    expertId: 'exp-1',
    roundIndex: 1,
    status: MatchStatus.WITHDRAWN,
    shortlistedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    withdrawalReason: 'Admin 响应太慢，我已经跟别的平台签约了。',
    opportunitySummary: '旧项目 A'
  }
];

export const MOCK_TEMPLATES: AdminTemplate[] = [
  {
    id: 't1',
    name: '需求摘要（中文）',
    type: 'summary',
    content: '1. 目标任务：{{task}}\n2. 输入/输出：{{format}}\n3. 投入节奏：{{intensity}}\n4. 预算：{{budget}}'
  },
  {
    id: 't2',
    name: '专家引荐邮件',
    type: 'email',
    content: '尊敬的 {{expert_name}}，很高兴向您推荐 {{client_name}} 的 {{project_name}} 项目。基于您的 {{skill_set}} 背景...'
  }
];
