
import { Need, NeedStatus, TaskType, ExpertProfile, TrustTier, EnglishLevel, MatchRecord, MatchStatus, ExpertTier, DataProductType, AdminTemplate } from '../types';

export const MOCK_EXPERTS: ExpertProfile[] = [
  {
    id: 'exp-1',
    name: '张伟 博士',
    domainTags: ['NLP', '法律合规', 'LLM评审'],
    summaryExperience: '10年以上法律科技经验，精通中国监管框架及法律文本分析。曾主导多个法律大模型的数据清洗与评估体系建设。',
    englishLevel: EnglishLevel.PROFICIENT,
    preferredWeeklyHours: 15,
    rateRange: '¥600 - ¥900 / 小时',
    verificationLink: 'https://linkedin.com/in/zhangwei',
    skills: ['NLP', 'Legal AI', 'Risk Assessment'],
    languages: ['Chinese', 'English'],
    hobbies: ['书法', '围棋'],
    certifications: [{ name: '中国法律职业资格', issuer: '司法部', year: '2012' }],
    portfolioUrl: '',
    additionalLinks: [],
    location: { country: 'China', state: 'Beijing', city: 'Beijing', postalCode: '100000', dob: '1985-01-01', isAuthorized: true, locationSameAsPhysical: true },
    availabilityToStart: '立即',
    timezone: 'UTC+8',
    workingHours: [
      { day: 'M', isAvailable: true, slots: [{ start: '09:00', end: '17:00' }] },
      { day: 'T', isAvailable: true, slots: [{ start: '09:00', end: '17:00' }] },
      { day: 'W', isAvailable: true, slots: [{ start: '09:00', end: '12:00' }] },
      { day: 'R', isAvailable: true, slots: [{ start: '09:00', end: '17:00' }] },
      { day: 'F', isAvailable: true, slots: [{ start: '09:00', end: '15:00' }] },
    ],
    domainInterests: ['Legal'],
    minCompensationFT: 0,
    minCompensationPT: 600,
    comms: { emailEnabled: true, smsEnabled: true, fullTimeOpps: true, partTimeOpps: true, referralOpps: true, jobNotifications: true, workUpdates: true },
    workExperiences: [{ id: 'w1', company: '法律科技领先企业', role: '首席技术专家', startDate: '2018-01', isCurrent: true, description: '负责构建法律大模型的训练评估体系。' }],
    educations: [{ id: 'e1', institution: '北京大学', degree: '博士', field: '计算机科学', graduationYear: '2014' }],
    trustTier: TrustTier.PROVEN,
    riskFlags: [],
  },
  {
    id: 'exp-2',
    name: 'Linda Schmidt',
    domainTags: ['Medical AI', 'Radiology', 'Dataset Curation'],
    summaryExperience: 'Senior Radiologist with 8 years of experience in AI-assisted diagnosis. Expertise in curating high-quality medical imaging datasets for model fine-tuning.',
    englishLevel: EnglishLevel.NATIVE,
    preferredWeeklyHours: 10,
    rateRange: '€150 - €220 / Hour',
    verificationLink: 'https://orcid.org/linda-schmidt',
    skills: ['Radiology', 'Data Labeling', 'Clinical Trials'],
    languages: ['German', 'English'],
    hobbies: ['Photography'],
    certifications: [{ name: 'Medical Board Certified', issuer: 'BÄK', year: '2016' }],
    portfolioUrl: '',
    additionalLinks: [],
    location: { country: 'Germany', state: 'Berlin', city: 'Berlin', postalCode: '10115', dob: '1982-04-12', isAuthorized: true, locationSameAsPhysical: true },
    availabilityToStart: '1 Week',
    timezone: 'UTC+1',
    workingHours: [],
    domainInterests: ['Medical'],
    minCompensationFT: 0,
    minCompensationPT: 120,
    comms: { emailEnabled: true, smsEnabled: true, fullTimeOpps: false, partTimeOpps: true, referralOpps: true, jobNotifications: true, workUpdates: true },
    workExperiences: [{ id: 'w2a', company: 'Berlin Charité Hospital', role: 'Senior Radiologist', startDate: '2016-03', isCurrent: true, description: 'Leading AI-assisted diagnosis research and curating medical imaging datasets.' }],
    educations: [{ id: 'e2a', institution: 'Humboldt University', degree: 'MD, PhD', field: 'Radiology', graduationYear: '2015' }],
    trustTier: TrustTier.PROVEN,
    riskFlags: [],
  },
  {
    id: 'exp-3',
    name: 'Chen Wei',
    domainTags: ['Python', 'System Red Teaming', 'Safety'],
    summaryExperience: 'Software Security Engineer specialized in LLM jailbreaking and safety alignment testing. Previously at a top-tier global cloud provider.',
    englishLevel: EnglishLevel.PROFICIENT,
    preferredWeeklyHours: 20,
    rateRange: '¥500 - ¥800 / 小时',
    verificationLink: '',
    skills: ['Cybersecurity', 'Python', 'Adversarial Attacks'],
    languages: ['Chinese', 'English'],
    hobbies: [],
    certifications: [],
    portfolioUrl: '',
    additionalLinks: [],
    location: { country: 'China', state: 'Guangdong', city: 'Shenzhen', postalCode: '518000', dob: '1991-09-30', isAuthorized: true, locationSameAsPhysical: true },
    availabilityToStart: '立即',
    timezone: 'UTC+8',
    workingHours: [],
    domainInterests: ['Security'],
    minCompensationFT: 0,
    minCompensationPT: 500,
    comms: { emailEnabled: true, smsEnabled: true, fullTimeOpps: true, partTimeOpps: true, referralOpps: true, jobNotifications: true, workUpdates: true },
    workExperiences: [{ id: 'w3a', company: '全球顶级云服务商', role: '安全工程师', startDate: '2019-06', isCurrent: true, description: '负责LLM安全对抗测试与红队评估。' }],
    educations: [{ id: 'e3a', institution: '中国科学技术大学', degree: '硕士', field: '信息安全', graduationYear: '2017' }],
    trustTier: TrustTier.SCREENED,
    riskFlags: [],
  },
  {
    id: 'exp-4',
    name: '刘芳',
    domainTags: ['多模态', '视觉模型', '投研分析'],
    summaryExperience: '前视觉AI初创公司首席算法工程师。在多模态理解与生成式AI的Post-training数据构建方面有极深造诣。',
    englishLevel: EnglishLevel.PROFICIENT,
    preferredWeeklyHours: 12,
    rateRange: '¥800 - ¥1200 / 小时',
    verificationLink: 'https://scholar.google.com/liufang',
    skills: ['Computer Vision', 'Multimodal', 'Financial Modeling'],
    languages: ['Chinese', 'English'],
    hobbies: ['Chess', 'Travelling'],
    certifications: [],
    portfolioUrl: '',
    additionalLinks: [],
    location: { country: 'China', state: 'Shanghai', city: 'Shanghai', postalCode: '200000', dob: '1992-05-15', isAuthorized: true, locationSameAsPhysical: true },
    availabilityToStart: '立即',
    timezone: 'UTC+8',
    workingHours: [
      { day: 'M', isAvailable: true, slots: [{ start: '10:00', end: '18:00' }] },
      { day: 'T', isAvailable: true, slots: [{ start: '10:00', end: '18:00' }] },
      { day: 'W', isAvailable: true, slots: [{ start: '14:00', end: '18:00' }] },
      { day: 'R', isAvailable: true, slots: [{ start: '10:00', end: '18:00' }] },
      { day: 'F', isAvailable: false, slots: [] },
    ],
    domainInterests: ['AI', 'Finance'],
    minCompensationFT: 0,
    minCompensationPT: 800,
    comms: { emailEnabled: true, smsEnabled: true, fullTimeOpps: true, partTimeOpps: true, referralOpps: true, jobNotifications: true, workUpdates: true },
    workExperiences: [{ id: 'w2', company: '视觉AI初创公司', role: '首席算法', startDate: '2019-06', isCurrent: true, description: '主导多模态大模型的研发。' }],
    educations: [{ id: 'e2', institution: '清华大学', degree: '硕士', field: '人工智能', graduationYear: '2018' }],
    trustTier: TrustTier.SCREENED,
    riskFlags: [],
  },
  {
    id: 'exp-5',
    name: '王明杰',
    domainTags: ['法律AI', '合同审查', '知识产权'],
    summaryExperience: '8年大型律所合伙人经验，擅长合同审查与知识产权纠纷。参与过多个法律AI产品的标注指南设计。',
    englishLevel: EnglishLevel.PROFICIENT,
    preferredWeeklyHours: 8,
    rateRange: '¥700 - ¥1000 / 小时',
    verificationLink: '',
    skills: ['Contract Review', 'IP Law', 'Legal NLP'],
    languages: ['Chinese', 'English'],
    hobbies: ['Reading'],
    certifications: [{ name: '中国律师执业证', issuer: '司法部', year: '2014' }],
    portfolioUrl: '',
    additionalLinks: [],
    location: { country: 'China', state: 'Shanghai', city: 'Shanghai', postalCode: '200040', dob: '1988-03-22', isAuthorized: true, locationSameAsPhysical: true },
    availabilityToStart: '2周内',
    timezone: 'UTC+8',
    workingHours: [],
    domainInterests: ['Legal'],
    minCompensationFT: 0,
    minCompensationPT: 700,
    comms: { emailEnabled: true, smsEnabled: true, fullTimeOpps: false, partTimeOpps: true, referralOpps: true, jobNotifications: true, workUpdates: true },
    workExperiences: [{ id: 'w5', company: '金杜律师事务所', role: '高级合伙人', startDate: '2016-01', isCurrent: true, description: '主攻科技公司知识产权与合同法务。' }],
    educations: [{ id: 'e5', institution: '中国政法大学', degree: '法学硕士', field: '知识产权法', graduationYear: '2013' }],
    trustTier: TrustTier.PROVEN,
    riskFlags: [],
  },
  {
    id: 'exp-6',
    name: '赵雅琴',
    domainTags: ['法律合规', '证券法', '金融监管'],
    summaryExperience: '12年证券法律从业经验，精通中国证监会监管框架。曾参与3个上市公司IPO法律顾问工作。',
    englishLevel: EnglishLevel.PROFICIENT,
    preferredWeeklyHours: 10,
    rateRange: '¥900 - ¥1500 / 小时',
    verificationLink: 'https://linkedin.com/in/zhaoyaqin',
    skills: ['Securities Law', 'Compliance', 'Regulatory Framework'],
    languages: ['Chinese', 'English'],
    hobbies: ['Piano', 'Yoga'],
    certifications: [{ name: '证券从业资格', issuer: '中国证监会', year: '2011' }, { name: '中国律师执业证', issuer: '司法部', year: '2010' }],
    portfolioUrl: '',
    additionalLinks: [],
    location: { country: 'China', state: 'Beijing', city: 'Beijing', postalCode: '100020', dob: '1986-07-15', isAuthorized: true, locationSameAsPhysical: true },
    availabilityToStart: '立即',
    timezone: 'UTC+8',
    workingHours: [],
    domainInterests: ['Legal', 'Finance'],
    minCompensationFT: 0,
    minCompensationPT: 900,
    comms: { emailEnabled: true, smsEnabled: true, fullTimeOpps: true, partTimeOpps: true, referralOpps: true, jobNotifications: true, workUpdates: true },
    workExperiences: [{ id: 'w6', company: '方达律师事务所', role: '资深律师', startDate: '2014-03', isCurrent: true, description: '专注证券法律合规与IPO法律顾问。' }],
    educations: [{ id: 'e6', institution: '北京大学', degree: '法学博士', field: '经济法', graduationYear: '2012' }],
    trustTier: TrustTier.PROVEN,
    riskFlags: [],
  },
];

// Demo Need B: 招募达标需求 (SHORTLISTED) - 有6位专家待评审
export const MOCK_NEEDS: Need[] = [
  {
    id: 'need-101',
    customerId: 'cust-1',
    customerOrgName: '神经网络科技 (NeuralTech)',
    domainArea: '法律推理评估 (Round 2)',
    masterDomain: 'Legal',
    subDomain: 'Chinese Corporate Law',
    taskType: TaskType.REVIEW,
    expertTier: ExpertTier.PRINCIPAL,
    dataProductType: DataProductType.EVAL,
    taskDescription: '评审500组中文法律QA对。需要寻找资深的专家，且必须具备执业背景。',
    intensityHours: 15,
    timeline: '4周',
    languageRequirement: '中文（母语）',
    budgetRange: '¥800 - ¥1200 / 小时',
    status: NeedStatus.SHORTLISTED,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    shortlist: ['exp-1', 'exp-3', 'exp-4', 'exp-5', 'exp-6'],
    shortlistReviewStatuses: {
      'exp-1': { status: 'pending' },
      'exp-3': { status: 'pending' },
      'exp-4': { status: 'pending' },
      'exp-5': { status: 'pending' },
      'exp-6': { status: 'pending' },
    },
    roundIndex: 2,
    clarificationLog: [],
    isApproved: true,
    pendingActionBy: 'customer',
    replacementCount: 0,
    ttfs_hours: 12,
    recruitmentSentCount: 15,
    recruitmentRespondedCount: 6,
    recruitmentTargetCount: 5,
  },
  // Demo Need C: 匹配成功需求 (MATCHED) - 可填写 Feedback
  {
    id: 'need-matched-001',
    customerId: 'cust-1',
    customerOrgName: '神经网络科技 (NeuralTech)',
    domainArea: '多模态报表分析',
    masterDomain: 'Finance',
    subDomain: 'Investment Research',
    taskType: TaskType.CONSULTING,
    expertTier: ExpertTier.SENIOR,
    dataProductType: DataProductType.RLHF,
    taskDescription: '对模型生成的财报分析进行真实性核查与风格对齐。需要具备CFA或同等金融分析背景。',
    intensityHours: 10,
    timeline: '3个月',
    languageRequirement: '英文',
    budgetRange: '$150/hr',
    status: NeedStatus.MATCHED,
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    shortlist: ['exp-4'],
    shortlistReviewStatuses: { 'exp-4': { status: 'approved', timestamp: new Date(Date.now() - 86400000 * 3).toISOString() } },
    roundIndex: 1,
    clarificationLog: [],
    pendingActionBy: 'customer',
    isApproved: true,
    aiSummary: '1. 领域：财务报表多模态分析；2. 核心任务：Hallucination Check & Style Alignment；3. 目标：高保真研报输出。',
    replacementCount: 0,
    ttfs_hours: 24,
    ttd_days: 3,
    recruitmentSentCount: 8,
    recruitmentRespondedCount: 4,
    recruitmentTargetCount: 3,
  }
];

// Expert inbox: opportunities received by the expert
export const MOCK_MATCHES: MatchRecord[] = [
  {
    id: 'match-new-1',
    needId: 'need-ext-001',
    expertId: 'exp-4',
    roundIndex: 1,
    status: MatchStatus.RECEIVED_SUMMARY,
    shortlistedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    opportunitySummary: '法律推理大模型评估：评审500组中文法律QA对，寻找具备执业背景的资深法律专家。',
    payRange: '¥800 - ¥1,200 / hr',
    hoursPerWeek: 15,
    timelineEstimate: '4周'
  },
  {
    id: 'match-new-2',
    needId: 'need-ext-002',
    expertId: 'exp-4',
    roundIndex: 1,
    status: MatchStatus.RECEIVED_SUMMARY,
    shortlistedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    opportunitySummary: '金融多模态报表分析：对AI生成的财报分析进行真实性核查与对齐，要求CFA或同等背景。',
    payRange: '$120 - $180 / hr',
    hoursPerWeek: 10,
    timelineEstimate: '3个月'
  },
  {
    id: 'match-active-1',
    needId: 'need-matched-001',
    expertId: 'exp-4',
    roundIndex: 1,
    status: MatchStatus.MEETING_SCHEDULED,
    shortlistedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    meetingScheduledAt: new Date(Date.now() + 86400000).toISOString(),
    opportunitySummary: '多模态报表分析 - 约谈已确认',
    payRange: '$150 / hr',
    hoursPerWeek: 10,
    timelineEstimate: '3个月'
  },
];

export const MOCK_TEMPLATES: AdminTemplate[] = [
  {
    id: 't1',
    name: '需求摘要（中文）',
    type: 'summary',
    content: '1. 目标任务：{{task}}\n2. 输入/输出：{{format}}\n3. 投入节奏：{{intensity}}\n4. 预算：{{budget}}'
  },
  {
    id: 't2',
    name: '专家引荐邮件',
    type: 'email',
    content: '尊敬的 {{expert_name}}，很高兴向您推荐 {{client_name}} 的 {{project_name}} 项目。基于您的 {{skill_set}} 背景...'
  }
];
